<?php

namespace SoniaBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDistinct($id)
    {
        $Query=$this->getEntityManager()->createQuery("select A from AppBundle:User A where A.id != :id ")
            ->setParameter('id','%'.$id.'%');
        return $Query->getResult();
    }
}
