<?php

namespace SoniaBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{/*
    public function findDistinct($id)
    {
        $Query=$this->getEntityManager()->createQuery("select A from AppBundle:User A where A.id != :id ")
            ->setParameter('id','%'.$id.'%');
        return $Query->getResult();
    }

    public function findT($event,$idU)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT A FROM user_byevent A WHERE A.user_id = :idU AND A.event_id = :event ")
            ->setParameter('event', $event)->setParameter('idU', $idU);
        return $query->getResult();
    }*/

    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM SoniaBundle:Event p
                WHERE p.nomEvent LIKE :str or p.typeEvent LIKE :str or  p.dateEvent LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
    public function findEntitiesByStringFront($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM SoniaBundle:Event p
                WHERE p.nomEvent LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}
