<?php

namespace SoniaBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByNumber(){
        $query= $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT (p.id)
                FROM SoniaBundle:Notification p '
            );
           return $result= $query->getSingleScalarResult();
    }
}
