<?php

namespace SoniaBundle\Repository;

/**
 * ParticcipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticcipationRepository extends \Doctrine\ORM\EntityRepository
{
}
