admin_AddAccount:
    path:     /
    defaults: { _controller: AdminBundle:Account:AddAccount }
admin_UpdateAccount:
    path:     /UpdateAccount/{id}
    defaults: { _controller: AdminBundle:Account:UpdateAccount }
admin_AddClasse:
    path:     /AddClasse
    defaults: { _controller: AdminBundle:Classe:AddClasse }
admin_DeleteClasse:
    path:     /DeleteClasse/{classId}
    defaults: { _controller: AdminBundle:Classe:DeleteClasse }
admin_UpdateClasse:
    path:     /UpdateClasse/{classId}
    defaults: { _controller: AdminBundle:Classe:UpdateClasse }
admin_AddSubject:
    path:     /AddSubject
    defaults: { _controller: AdminBundle:Subject:AddSubject }
admin_UpdateSubject:
    path:     /UpdateSubject/{subjectId}
    defaults: { _controller: AdminBundle:Subject:UpdateSubject }
admin_DeleteSubject:
    path:     /DeleteSubject/{subjectId}
    defaults: { _controller: AdminBundle:Subject:DeleteSubject }
admin_AddSchedule:
    path:     /AddSchedule
    defaults: { _controller: AdminBundle:Schedule:AddSchedule }