admin_AddAccount:
    path:     /
    defaults: { _controller: AdminBundle:Account:AddAccount }
admin_UpdateAccount:
    path:     /UpdateAccount/{id}
    defaults: { _controller: AdminBundle:Account:UpdateAccount }
