etudiant_homepage:
    path:     /
    defaults: { _controller: EtudiantBundle:Default:index }
etudiant_inscrit:
    path:     /inscrit
    defaults: { _controller: EtudiantBundle:Etudiant:etudiantinscrit }
etudiant_created:
    path:     /created
    defaults: { _controller: EtudiantBundle:Etudiant:accoutcreated }
etudiant_approve:
    path:     /approve
    defaults: { _controller: EtudiantBundle:Etudiant:accoutaproving }
etudiant_delete:
    path:     /delete/{id}
    defaults: { _controller: EtudiantBundle:Etudiant:deleteapprove }
etudiant_approving:
    path:     /aproved/{id}
    defaults: { _controller: EtudiantBundle:Etudiant:approveEtudiant }
etudiant_list:
    path:     /listeStudents
    defaults: { _controller: EtudiantBundle:Etudiant:allstudents }
etudiant_affectto:
    path:     /affectto/{id}
    defaults: { _controller: EtudiantBundle:Etudiant:affecttoclass }
etudiant_addmanually :
    path:     /addStudentManually
    defaults: { _controller: EtudiantBundle:Etudiant:AddStudentManually }
etudiant_accountSetting :
    path:     /accountSetting/{id}
    defaults: { _controller: EtudiantBundle:Etudiant:Accountsettings }
etudiant_accountdisable :
    path:     /disableaccount/{id}
    defaults: { _controller: EtudiantBundle:Etudiant:disableAccount }
etudiant_submitreclamation :
    path:     /reclamation
    defaults: { _controller: EtudiantBundle:Reclamation:submitReclamation }
etudaint_addsubject :
    path:     /addsubject
    defaults: { _controller: EtudiantBundle:Forum:AddSubject}
etudaint_subjectreview :
    path:     /allsubjects
    defaults: { _controller: EtudiantBundle:Forum:getSubjects}
etudaint_subjectapprove :
    path:     /subjectaprove/{id}
    defaults: { _controller: EtudiantBundle:Forum:approveSubject}