etudiant_homepage:
    path:     /
    defaults: { _controller: EtudiantBundle:Default:index }
etudiant_inscrit:
    path:     /inscrit
    defaults: { _controller: EtudiantBundle:Etudiant:etudiantinscrit }
etudiant_created:
    path:     /created
    defaults: { _controller: EtudiantBundle:Etudiant:accoutcreated }
etudiant_approve:
    path:     /approve
    defaults: { _controller: EtudiantBundle:Etudiant:accoutaproving }
etudiant_delete:
    path:     /delete/{id}
    defaults: { _controller: EtudiantBundle:Etudiant:deleteapprove }
etudiant_approving:
    path:     /aproved/{id}
    defaults: { _controller: EtudiantBundle:Etudiant:approveEtudiant }
etudiant_list:
    path:     /listeStudents
    defaults: { _controller: EtudiantBundle:Etudiant:allstudents }
etudiant_affectto:
    path:     /affectto/{id}
    defaults: { _controller: EtudiantBundle:Etudiant:affecttoclass }
