etudiant:
    resource: "@EtudiantBundle/Resources/config/routing.yml"
    prefix:   /etudiant

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation


