sonia:
    resource: "@SoniaBundle/Resources/config/routing.yml"
    prefix:   /sonia

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation


