teacher:
    resource: "@TeacherBundle/Resources/config/routing.yml"
    prefix:   /teacher

etudiant:
    resource: "@EtudiantBundle/Resources/config/routing.yml"
    prefix:   /etudiant

parent:
    resource: "@ParentBundle/Resources/config/routing.yml"
    prefix:   /parent

sonia:
    resource: "@SoniaBundle/Resources/config/routing.yml"
    prefix:   /sonia

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation


