<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKko3acb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKko3acb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKko3acb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKko3acb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKko3acb\appProdProjectContainer([
    'container.build_hash' => 'Kko3acb',
    'container.build_id' => 'aef44c09',
    'container.build_time' => 1581415161,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKko3acb');
