<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLuj1i3s\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLuj1i3s/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLuj1i3s.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLuj1i3s\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLuj1i3s\appProdProjectContainer([
    'container.build_hash' => 'Luj1i3s',
    'container.build_id' => 'fe8be9a2',
    'container.build_time' => 1582720037,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLuj1i3s');
