<?php

namespace EtudiantBundle\Repository;
use EtudiantBundle\Entity\Classe;
/**
 * ClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findClasses($variable)
    {

        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT c
            FROM EtudiantBundle\Entity\Classe c
            WHERE c.class_name LIKE :variable'
        )->setParameter('variable', '%'.$variable.'%');

        // returns an array of Product objects
        return $query->getResult();
    }
}
