<?php

namespace EtudiantBundle\Repository;

/**
 * EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends \Doctrine\ORM\EntityRepository
{
    public function findClasses($idclasse)
    {

        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT c.class_name
            FROM EtudiantBundle\Entity\Classe c, AppBundle\Entity\User U 
            WHERE c.id = U.id
            AND c.id = :idclasse
            '
        )->setParameter('idclasse', $idclasse);

        // returns an array of Product objects
        return $query->getResult();
    }


}
