<?php

namespace EtudiantBundle\Repository;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserByName($searchTitle){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u
                FROM EtudiantBundle:Forum u
                WHERE u.title LIKE :searchTitle '
            )
            ->setParameter('searchTitle', '%'.$searchTitle.'%')
            ->getResult();
    }
}
