<?php

namespace EtudiantBundle\Repository;

/**
 * VotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VotesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findyesvotes($id)
    {
        return $this->createQueryBuilder('votes')
            ->select('COUNT(votes)')
            ->where('votes.status = true')
            ->getQuery()
            ->getSingleScalarResult();
    }
    public function dislikes($id)
    {
        return $this->createQueryBuilder('votes')
            ->select('COUNT(votes)')
            ->where('votes.status = false')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function voterorno($voter)
    {
        return $this->createQueryBuilder('votes')
            ->select('votes')
            ->where('votes.voter = :voter')
            ->setParameter(':voter',$voter)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
