<?php

namespace TeacherBundle\Repository;

/**
 * AbsentTeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsentTeacherRepository extends \Doctrine\ORM\EntityRepository
{
}
