<?php

namespace TeacherBundle\Repository;

/**
 * DelayTeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelayTeacherRepository extends \Doctrine\ORM\EntityRepository
{
}
