<?php

namespace TeacherBundle\Repository;

/**
 * MarksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarksRepository extends \Doctrine\ORM\EntityRepository
{
}
