sonia_homepage:
    path:     /
    defaults: { _controller: SoniaBundle:Default:index }
afficherEvent:
    path:     /afficherEvent
    defaults: { _controller: SoniaBundle:Event:AfficherEvent }
ajouterEvent:
    path:     /ajouterEvent
    defaults: { _controller: SoniaBundle:Event:AjouterEvent }
ajouterActivite:
    path:     /ajouterActivite
    defaults: { _controller: SoniaBundle:Event:AjouterActivite }
ajouterTrip:
    path:     /ajouterTrip
    defaults: { _controller: SoniaBundle:Event:AjouterFieldTrip }
ajouterCompetiton:
    path:     /ajouterCompetiton
    defaults: { _controller: SoniaBundle:Event:AjouterCompetition }
modifierEvent:
    path:     /modifierEvent/{id}
    defaults: { _controller: SoniaBundle:Event:UpdateEvent }
supprimerEvent:
    path:     /supprimerEvent/{id}
    defaults: { _controller: SoniaBundle:Event:DeleteEvent }
afficherEventFront:
    path:     /afficherEventFront
    defaults: { _controller: SoniaBundle:Event:AfficherEventFront }
afficherEventDetail:
    path:     /afficherEventDetail/{id}
    defaults: { _controller: SoniaBundle:Event:DetailEvent }
ParticiperEvent:
    path:     /ParticiperEvent/{id}
    defaults: { _controller: SoniaBundle:Event:Participate }
afficherClub:
    path:     /afficherClub
    defaults: { _controller: SoniaBundle:Club:AfficherClub }
ajouterClub:
    path:     /ajouterClub
    defaults: { _controller: SoniaBundle:Club:AjouterClub }
modifierClub:
    path:     /modifierClub/{id}
    defaults: { _controller: SoniaBundle:Club:UpdateClub }
supprimerClub:
    path:     /supprimerClub/{id}
    defaults: { _controller: SoniaBundle:Club:DeleteClub }