<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container762j6fq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container762j6fq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container762j6fq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container762j6fq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container762j6fq\appDevDebugProjectContainer([
    'container.build_hash' => '762j6fq',
    'container.build_id' => '7fe6ca5d',
    'container.build_time' => 1581188278,
], __DIR__.\DIRECTORY_SEPARATOR.'Container762j6fq');
