<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWxcfzyj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWxcfzyj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWxcfzyj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWxcfzyj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWxcfzyj\appDevDebugProjectContainer([
    'container.build_hash' => 'Wxcfzyj',
    'container.build_id' => 'b8b3dd0d',
    'container.build_time' => 1582146004,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWxcfzyj');
