<?php

namespace Proxies\__CG__\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Schedule extends \AdminBundle\Entity\Schedule implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'scheduleId', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'seance1', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'seance2', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'seance3', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'seance4', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'day', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'week', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'classe'];
        }

        return ['__isInitialized__', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'scheduleId', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'seance1', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'seance2', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'seance3', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'seance4', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'day', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'week', '' . "\0" . 'AdminBundle\\Entity\\Schedule' . "\0" . 'classe'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Schedule $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getClasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasse', []);

        return parent::getClasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasse($classe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasse', [$classe]);

        return parent::setClasse($classe);
    }

    /**
     * {@inheritDoc}
     */
    public function getScheduleId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getScheduleId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScheduleId', []);

        return parent::getScheduleId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeance1($seance1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeance1', [$seance1]);

        return parent::setSeance1($seance1);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeance1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeance1', []);

        return parent::getSeance1();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeance2($seance2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeance2', [$seance2]);

        return parent::setSeance2($seance2);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeance2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeance2', []);

        return parent::getSeance2();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeance3($seance3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeance3', [$seance3]);

        return parent::setSeance3($seance3);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeance3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeance3', []);

        return parent::getSeance3();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeance4($seance4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeance4', [$seance4]);

        return parent::setSeance4($seance4);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeance4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeance4', []);

        return parent::getSeance4();
    }

    /**
     * {@inheritDoc}
     */
    public function setDay($day)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDay', [$day]);

        return parent::setDay($day);
    }

    /**
     * {@inheritDoc}
     */
    public function getDay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDay', []);

        return parent::getDay();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeek($week)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeek', [$week]);

        return parent::setWeek($week);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeek()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeek', []);

        return parent::getWeek();
    }

}
